# Specify configuration of mutant validation plots

published_metadata: data/Crawford_SuppFile2.csv # this is Supplementary File 2 from Crawford et al. (2020)

# path to file containing rbd depletion fold change data
moderna_depletions: results/rbd_absorptions/TableS1.csv
haarvi_depletions: data/haarvi_rbd_depletion_foldchange_ic50.csv

neut_input_files: # make sure it is in this format:
  data/210308_mutneuts.csv: 210308
  data/210312_mutneuts.csv: 210312

# enter all the samples and stuff to ignore here
neut_samples_ignore: False
neut_ignore_viruses:
  E484K: 210308 # these were repeated on 210312

# the neutralization limit of detection is equal to the starting dilution
NT50_LOD: 25

validated_samples:
  M06-day-119: M06 (day 119)
  M11-day-119: M11 (day 119)
  M05-day-119: M05 (day 119)
  M03-day-119: M03 (day 119)
  M12-day-119: M12 (day 119)
  M14-day-119: M14 (day 119)
  24C_d104: participant C (day 104)
  22C_d104: participant E (day 104)
  23C_d102: participant I (day 102)
  1C_d113: participant B (day 113)
  23_d120: participant A (day 120)
  25_d94: participant G (day 94)

sample_types:
  M06 (day 119): vaccine
  M11 (day 119): vaccine
  M05 (day 119): vaccine
  M03 (day 119): vaccine
  M12 (day 119): vaccine
  M14 (day 119): vaccine
  participant C (day 104): convalescent
  participant E (day 104): convalescent
  participant I (day 102): convalescent
  participant B (day 113): convalescent
  participant A (day 120): convalescent
  participant G (day 94): convalescent

viruses:
  wildtype: naturally-occurring
  P384R: naturally-occurring
  K417N: naturally-occurring
  G446V: naturally-occurring
  L452R: naturally-occurring
  F456A: not naturally-occurring
  E484P: not naturally-occurring
  E484K: naturally-occurring
  K417N-G446V-E484K: not naturally-occurring
  RBD antibodies depleted: not naturally-occurring

epitope_colors:
  - '#FFFFFF'# naturally-occurring
  - '#999999' # not naturally-occurring

# epitope_colors:
#   - '#E52794' # class 1
#   - '#6A0DAD' # class 2
#   - '#66CCEE' # class 3
#   - '#E69F00' # class 4
#   - '#FFFFFF' # other

map_conditions:
  M06-day-119_80: M06 (day 119)
  M11-day-119_200: M11 (day 119)
  M05-day-119_500: M05 (day 119)
  M03-day-119_200: M03 (day 119)
  M12-day-119_200: M12 (day 119)
  M14-day-119_500: M14 (day 119)
  24C_d104_200: participant C (day 104)
  22C_d104_200: participant E (day 104)
  23C_d102_80: participant I (day 102)
  1C_d113_200: participant B (day 113)
  23_d120_500: participant A (day 120)
  25_d94_200: participant G (day 94)

# viral entry titers
titer_input_file: data/entry_titers_all.csv
